### ISSUE TITLE
WP standard setup

### ISSUE THREAD

**Issue by ktenman** [ktenman/veebiarendus#19]
https://veebiblog.wordpress.com/2016/10/04/4-postitus-wp-paigaldus/

Teema:
http://themeisle.com/demo/?theme=Llorix+One&ref=4560

**Comment by ktenman** [comment]
https://veebiblog.wordpress.com/2016/10/04/4-postitus-wp-paigaldus/

**Comment by kardoj** [comment]
Server on püsti, WP jookseb, kujundus on paigas.
